import Head from "next/head";
import Carousal from "../components/home/Carousal";
import Hero from "../components/home/Hero";
import Stats from "../components/home/Stats";
import Testimonials from "../components/home/Testimonials";
import Navbar from "../components/common/Navbar";
import Footer from "../components/common/Footer";
import CoreTeam from "../components/home/CoreTeam";
import Donate from "../components/home/Donate";
import About from "../components/home/About";

export default function Home() {
    return ( <
        >
        <
        Head >
        <
        title > Old Heal < /title> <
        link rel = "icon"
        href = "/logo.jpeg" / > { /* Meta Tags Dynamically generated by metaseo.itsvg.in */ } <
        meta name = "title"
        content = "Old Heal" / >
        <
        meta name = "description"
        content = "We reduce the wastage of food by using it for a good cause and provide a healthy meal to kids so that they can sleep with no hunger." /
        >
        <
        meta name = "copyright"
        content = "VishwaGauravIn" / >

        <
        meta property = "og:type"
        content = "website" / >
        <
        meta property = "og:url"
        content = "" / >
        <
        meta property = "og:title"
        content = "Old Heal" / >
        <
        meta property = "og:description"
        content = "We reduce the wastage of food by using it for a good cause and provide a healthy meal to kids so that they can sleep with no hunger." /
        >
        <
        meta property = "og:image"
        content = "" / >
        <
        meta property = "twitter:card"
        content = " " / >
        <
        meta property = "twitter:url"
        content = "" / >
        <
        meta property = "twitter:title"
        content = "Old Heal" / >
        <
        meta property = "twitter:description"
        content = "We reduce the wastage of food by using it for a good cause and provide a healthy meal to kids so that they can sleep with no hunger." /
        >
        <
        meta property = "twitter:image"
        content = "" / >
        <
        /Head>

        <
        main className = "" >
        <
        Navbar / >
        <
        Hero / >
        <
        Carousal / >
        <
        Stats / >
        <
        Donate / >
        <
        Testimonials / >
        <
        CoreTeam / >
        <
        About / >
        <
        /main>

        <
        Footer / >
        <
        />
    );
}